src/config/daos/daosDevelopment.ts, src/config/daos/daosLocalhost.example.ts, src/config/daos/daosProduction.ts
✨ **Updates**
- Adds `snapshotHub.proposalResolver` for development and production daos
- Adds actual `webhookID` for production `muse0`
=> Update daos with resolvers and webhook ID for prod Muse0

Dockerfile.dev
Produces a much smaller container (over 50% smaller!) for local development.
- Uses `node:16-alpine` in `Dockerfile.dev`
- Installs `bash` in `Dockerfile.dev`
=> Uses `node:16-alpine` for `Dockerfile.dev`

src/config/daos/daosProduction.ts
- Muse0 have an incorrect `baseURL` which produces an incorrect URL inside Discord notifications
=> Fixes wrong `baseURL` for prod Muse0

src/config/daos/daosDevelopment.ts, src/config/daos/daosProduction.ts, src/config/snapshotHubResolvers.ts, src/services/dao/getProposalAdapterID.ts, src/services/dao/getProposalAdapterID.unit.test.ts, src/services/snapshotHub/index.ts, src/services/snapshotHub/legacyTributeDraftResolver.ts, src/services/snapshotHub/legacyTributeDraftResolver.unit.test.ts, src/services/snapshotHub/legacyTributeProposalResolver.ts, src/services/snapshotHub/snapshotHubResolverSelector.ts, src/services/snapshotHub/snapshotHubResolverSelector.unit.test.ts, src/services/snapshotHub/types.ts, src/webhook-tasks/actions/snapshotHub/index.ts, src/webhook-tasks/actions/snapshotHub/legacyTributeDraftCreated.ts, src/webhook-tasks/actions/snapshotHub/legacyTributeDraftCreated.unit.test.ts, src/webhook-tasks/actions/snapshotHub/legacyTributeGovernanceProposalCreated.ts, src/webhook-tasks/actions/snapshotHub/legacyTributeGovernanceProposalCreatedAction.unit.test.ts, src/webhook-tasks/actions/web3/subscribeLogs/sponsoredProposal.ts, src/webhook-tasks/actions/web3/subscribeLogs/sponsoredProposal.unit.test.ts, src/webhook-tasks/runners/snapshotHub/proposalEventRunner.ts, src/webhook-tasks/runners/snapshotHub/proposalEventRunner.unit.test.ts, src/webhook-tasks/templates/snapshotHub/draftCreated.ts, src/webhook-tasks/templates/snapshotHub/index.ts, src/webhook-tasks/templates/snapshotHub/proposalCreated.ts, test/fixtures/fakeDaos.ts, test/fixtures/index.ts, test/fixtures/legacySnapshotHubDraft.ts, test/msw/serverHandlersREST.ts
Fixes #48 
When a snapshot hub draft is created Discord channels can now be notified.
🥳 **Adds**
- `legacyTributeDraftResolver` in order to properly get Snapshot Hub drafts
- `legacyTributeDraftCreated` snapshot hub action
- `draftCreated` template
✨ **Updates**
- Adds Muse0 to list of development DAOs
- Simplifies Snapshot Hub resolver selection via `snapshotHubResolverSelector`
- Adds `LEGACY_TRIBUTE_DRAFT` to list of snapshot hub resolvers
- Improves `getProposalAdapterID` to accept `adapterAddress` and skip a call to the chain
- Removes fallback template from snapshot governance action as it was running when it was not supposed to and provided little value.
- Updates exit conditions in snapshot governance action
- Updates exit conditions in sponsored proposal action
- Adds new …
=> Implements Snapshot Hub draft submissions -> Discord webhook

codecov.yml
- Adds `test` dir to ignored Codecov paths
=> Adds `codecov` config and ignore path for `test`

src/config/applications.ts
- The `APP_ENV` helper var was not correct as it was using the `index.ts` and `applications` was exported *before* `common`
=> Fixes `APP_ENV` import order bug

src/applications/floor-sweeper-poll/config.ts
✨ **Updates**
- remove trailing `/` from production `SWEEP_EXTERNAL_URL` (The trailing slash was appropriately resolved in the tools dapp and didn't actually break anything. This is just clean up to not have to rely on the dapp to handle.)
=> fix prod SWEEP_EXTERNAL_URL

src/config/daos/daosProduction.ts
---
✨ **Updates**
- Production DAOs config: adds `flamingo` (Moloch-based DAO) config for accessing the `FLOOR_SWEEPER_POLL_BOT`
=> Adds initial `flamingo` (moloch dao) prod config

src/config/applications.ts
- Updating application IDs after creating a new `Tribute Labs` Discord team under my original account and transferred ownership to Jarrel. My new "work" account was disabled by Discord, for some reason.
=> Updates `FLOOR_SWEEPER_POLL_BOT_ID` to match tribute labs team

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
✨ **Updates**
- Dev and Prod deployment workflows were updated to push the new image tags to `openlawteam/infrastructure` instead of `lao-backends` repo.
- You won't need to create releases on `openlawteam/infrastructure` repo to deploy to prod. You just need to create a release here, in this project, and that will get auto deployed to prod.
=> chore: update deployment workflows

prisma/migrations/20220221161349_/migration.sql, prisma/schema.prisma, src/applications/tribute-tools/commands/buy.ts, src/applications/tribute-tools/commands/fund.ts, src/applications/tribute-tools/commands/fund.unit.test.ts, src/applications/tribute-tools/config.ts, src/applications/tribute-tools/handlers/buy/buyPollReactionHandler.ts, src/applications/tribute-tools/handlers/buy/buyPollRemoveReactionHandler.ts, src/applications/tribute-tools/handlers/fund/fundPollReactionHandler.ts, src/applications/tribute-tools/handlers/fund/fundPollReactionHandler.unit.test.ts, src/applications/tribute-tools/handlers/fund/fundPollRemoveReactionHandler.ts, src/applications/tribute-tools/handlers/fund/fundPollRemoveReactionHandler.unit.test.ts, src/applications/tribute-tools/handlers/fund/index.ts, src/applications/tribute-tools/handlers/index.ts, src/applications/tribute-tools/main.ts, src/config/applications.ts, src/config/daos/daosDevelopment.ts, src/config/daos/daosLocalhost.example.ts, src/config/daos/daosProduction.ts, src/config/types.ts, test/fixtures/fakeDaos.ts
Fixes #81 
Adds a Discord command called `/fund` which takes a target address and an amount (in USDC) which is to be funded into the address.
🥳 **Adds**
- `fund_address_poll` DB table
- Adds Discord `/fund` command
- Adds handlers for reactions to the poll message
- Adds DAO configuration for `FUND`
- `BUY_ALLOWED_EMOJIS`->`THUMBS_EMOJIS`
=> Add `/fund` command

prisma/migrations/20220223161050_/migration.sql, prisma/schema.prisma, src/http-api/helpers/createHTTPError.ts, src/http-api/helpers/createHTTPError.unit.test.ts, src/http-api/helpers/index.ts, src/http-api/middleware/index.ts, src/http-api/middleware/tributeToolsTxWebhook.ts, src/http-api/middleware/tributeToolsTxWebhook.unit.test.ts, src/http-api/types.ts, test/fixtures/constants.ts
Fixes #87 
🥳 **Adds**
- `POST /webhook/tribute-tools-tx` HTTP API endpoint
- `tributeToolsTxWebhook` API handler
- `createHTTPError` helper
- `TributeToolsWebhookTxType`, `TributeToolsWebhookPayload`, `TributeToolsWebhookTxStatus` types
- `UUID_FIXTURE` test fixture
✨ **Updates**
- `txStatus` column to `floor_sweeper_poll`, `buy_nft_poll`, `fund_address_poll` tables
- `txHash` column to `floor_sweeper_poll`, `buy_nft_poll`, `fund_address_poll` tables
=> Adds webhook for sending a poll tx's status

package-lock.json, package.json, src/http-api/httpServer.ts, src/http-api/index.ts, src/http-api/middleware/db.ts, src/http-api/middleware/default.ts, src/http-api/middleware/error.ts, src/http-api/middleware/error.unit.test.ts, src/http-api/middleware/health.ts, src/http-api/middleware/index.ts, src/http-api/middleware/snapshotWebhook.ts, src/http-api/middleware/tributeTools/index.ts, src/http-api/middleware/tributeTools/router.ts, src/http-api/middleware/tributeTools/tributeToolsGetDaoTxs.ts, src/http-api/middleware/tributeTools/tributeToolsGetDaoTxs.unit.test.ts, src/http-api/middleware/tributeTools/tributeToolsGetTx.ts, src/http-api/middleware/tributeTools/tributeToolsGetTx.unit.test.ts, src/http-api/middleware/tributeTools/tributeToolsTxWebhook.ts, src/http-api/middleware/tributeTools/tributeToolsTxWebhook.unit.test.ts
Fixes #90 
🥳 **Adds**
- `GET .../tribute-tools/tx/<type>/<uuid>`
- `GET .../tribute-tools/tx/<daoName>/<type>`
- `@koa/router`, `@types/koa__router` packages
✨ **Updates**
- Handler registry was updated to accommodate `@koa/router` `Route`s
- `error` handler now returns JSON
=> HTTP Endpoints to get submitted transaction data for sweep, buy, fund

src/config/daos/daosProduction.ts
✨ **Updates**
- `metaverse` production `/buy` command thresholds configuration now align with Snapshot governance vote.
=> updates `metaverse` `/buy` thresholds to align with governance vote

README.md, package.json, prisma/migrations/20220303135522_/migration.sql, prisma/schema.prisma, src/applications/tribute-tools/getTributeToolsClient.ts, src/applications/tribute-tools/getTributeToolsClient.unit.test.ts, src/applications/tribute-tools/handlers/buy/buyPollReactionHandler.ts, src/applications/tribute-tools/handlers/buy/buyPollReactionHandler.unit.test.ts, src/applications/tribute-tools/handlers/fund/fundPollReactionHandler.ts, src/applications/tribute-tools/handlers/fund/fundPollReactionHandler.unit.test.ts, src/applications/tribute-tools/handlers/index.ts, src/applications/tribute-tools/handlers/notifyPollTxStatus.ts, src/applications/tribute-tools/handlers/notifyPollTxStatus.unit.test.ts, src/applications/tribute-tools/handlers/setPollTxStatus.ts, src/applications/tribute-tools/handlers/sweep/sweepEndedPollsHandler.ts, src/applications/tribute-tools/handlers/sweep/sweepEndedPollsHandler.unit.test.ts, src/applications/tribute-tools/index.ts, src/applications/tribute-tools/main.ts, src/applications/tribute-tools/main.unit.test.ts, src/http-api/middleware/tributeTools/tributeToolsTxWebhook.ts, src/http-api/middleware/tributeTools/tributeToolsTxWebhook.unit.test.ts
Fixes #95 
🥳 **Adds**
- `notifyPollTxStatus` handler for displaying a poll's transaction status
- `docker:migrate:dev` helper `package.json` script
- DB migration for adding `actionMessageID` column to `buy_nft_poll`, `floor_sweeper_poll`, `fund_address_poll`
- `getTributeToolsClient` helper to access instantiated Tribute Tools app Discord `Client` throughout app.
✨ **Updates**
- Tribute Tools app `Client` usages refactored with `getTributeToolsClient`
- `tributeToolsTxWebhook` API middleware now uses `notifyPollTxStatus`
- `README` DB migrations instructions
- Stores `actionMessageID` in database for `/buy`, `/fund`, `/sweep`
=> Display transaction status for `/buy`, `/sweep`, `/fund` polls

src/applications/tribute-tools/handlers/fund/fundPollReactionHandler.ts, src/applications/tribute-tools/handlers/fund/fundPollReactionHandler.unit.test.ts
Fixes #105 
- Adds `uuid` to external `LINK` URL for the Tribute Tools fund action.
=> adds `id=<UUID>` to `/fund` Tribute Tools `LINK`

prisma/migrations/20220310141922_/migration.sql, prisma/schema.prisma, src/applications/tribute-tools/commands/buy.ts, src/applications/tribute-tools/commands/buy.unit.test.ts, src/applications/tribute-tools/commands/fund.ts, src/applications/tribute-tools/commands/fund.unit.test.ts, src/applications/tribute-tools/commands/sweep.ts, src/applications/tribute-tools/commands/sweep.unit.test.ts, src/applications/tribute-tools/config.ts, src/applications/tribute-tools/handlers/buy/buyPollReactionHandler.unit.test.ts, src/applications/tribute-tools/handlers/cancelPollHandler.ts, src/applications/tribute-tools/handlers/cancelPollHandler.unit.test.ts, src/applications/tribute-tools/handlers/confirmCancelPollHandler.ts, src/applications/tribute-tools/handlers/confirmCancelPollHandler.unit.test.ts, src/applications/tribute-tools/handlers/index.ts, src/applications/tribute-tools/handlers/notifyPollTxStatus.ts, src/applications/tribute-tools/handlers/notifyPollTxStatus.unit.test.ts, src/applications/tribute-tools/main.ts, src/applications/tribute-tools/main.unit.test.ts, src/http-api/middleware/tributeTools/tributeToolsTxWebhook.ts
Fixes #93 
🥳 **Adds**
- DB migration for adding `isCancelled` to `buy_nft_poll`, `floor_sweeper_poll`, `fund_address_poll`
- Adds `Cancel poll` button to reply from `/buy`, `/fund`, `/sweep`
- `cancelPollHandler` for handling the click of the `Cancel poll` button
- `confirmCancelPollHandler` for handling confirmation of cancelling the poll
✨ **Updates**
- `notifyPollTxStatus` to remove the `Cancel poll` button if the tx status is successful.
- `main` to run the cancel poll handlers
=> Mark poll as cancelled

src/applications/tribute-tools/commands/buy.ts, src/applications/tribute-tools/commands/buy.unit.test.ts
Fixes #111 
✨ **Updates**
- Improves handling of response data validation from Gem
- Decreases API data response size by requesting less fields
- Information is now populated for the purchase of a single item inside an ERC-1155 standard contract.
=> Adds ERC-1155 support for `/buy`

src/config/common.ts, src/helpers/envCheck.ts, src/helpers/envCheck.unit.test.ts, src/helpers/getEnv.ts
- Empty `GEM_API_KEY` does not cause the startup env check to warn
- Improves types on `envCheck`, `getEnv` functions
- Slight refactor on `getEnv` and improves tests
=> Makes `GEM_API_KEY` optional

.github/workflows/codecov.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/prettier-lint.yml, .github/workflows/unit-tests.yml
- Adds [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) to `on:` list in GH Action files to provide the option to trigger builds from the CLI, REST or, UI
=> Adds `workflow_dispatch` to run GH Action manually if needed

src/services/snapshotHub/legacyTributeDraftResolver.unit.test.ts, src/services/snapshotHub/legacyTributeProposalResolver.unit.test.ts, test/fixtures/fakeDaos.ts, test/msw/serverHandlersREST.ts
- fixes flaky Snapshot mocked REST calls after `msw` upgrade
=> attempt to fix flaky snapshot tests

src/services/snapshotHub/legacyTributeDraftResolver.unit.test.ts, src/services/snapshotHub/legacyTributeProposalResolver.unit.test.ts
- Removes remaining references to `docker-host` in tests as it was causing `msw` to fail in CI
=> removes remaining references in tests to `http://docker-host`

src/config/discords/daos/daosProduction.ts
Fixes #138 
- Adds production DAO configuration for `bright` (Bright Opportunities DAO)
=> Adds DAO config for bright opportunities DAO

prisma/migrations/20220513131502_/migration.sql, prisma/schema.prisma, src/applications/tribute-tools/commands/fund.ts, src/applications/tribute-tools/commands/fund.unit.test.ts, src/applications/tribute-tools/handlers/cancelPollHandler.unit.test.ts, src/applications/tribute-tools/handlers/confirmCancelPollHandler.unit.test.ts, src/applications/tribute-tools/handlers/notifyPollTxStatus.unit.test.ts
Fixes #140 
✨ **Updates**
- DB Migration: sets `fund_address_poll`->`amountUSDC` to `DECIMAL(65,2)`
- Changes Discord slash command option type `amount_in_usdc` from `INTEGER` to `NUMBER`
=> Decimal support for `/fund`
