- README.md
✨ **Updates**
- Removes Node version
- Updates NPM version description
> `README` dependencies updates

- .github/workflows/unit-tests.yml
- jest.config.js
- package-lock.json
- package.json
- src/client.ts
- src/service/getWebhook.ts
- src/service/getWebhook.unit.test.ts
- src/service/index.ts
- test/singleton.ts
🥳 **Adds**
- Setup for Jest
- `jest`, `ts-jest`, `jest-mock-extended` packages
- adds unit test GH Action workflow
- Adds `getWebhookByWebhookID` and first tests
> Jest setup

- scripts/dev-start.sh
- src/events/web3/README.md
- src/events/web3/eventSignatures.ts
🥳 **Adds**
- `events/web3/README`
✨ **Updates**
- Docs in `dev-start.sh`
- Docs for `src/events/web3/eventSignatures.ts`
> adds better docs for directory of web3 events

- .github/workflows/prettier-lint.yml
- .github/workflows/unit-tests.yml
- src/webhook-tasks/actions/web3/subscribeLogs/sponsoredProposal.unit.test.ts
✨ **Updates**
- Updates Node version in GitHub Actions Workflow files to `16.x`
- Adds back in flaky test, which is not not flaky!
> Update Node version in GitHub Actions Workflows

- .github/workflows/deploy-dev.yml
Fixes the dev workflow to set the image tag using sed.
> Set img tag with sed

- src/config/daos/daosDevelopment.ts
- Adds real Discord webhook ID for `tribute` development DAO config
> Fixes webhookID for `tribute` development DAO

- src/config/daos/daosDevelopment.ts
- Fixes `muse0` dev DAO `baseURL`
> fixes dev muse0 dao `baseURL`

- .github/workflows/codecov.yml
- Runs codecov GH Action on pushes to branch `main`
> Updates codecov GH Action to run on pushes to `main`

- src/config/daos/daosDevelopment.ts
Part of #54 to test development configs
✨ **Updates**
- `metaverse` (NEON) config for Governance proposal creation notifications (dev)
- `fashion` (Red) config for Governance proposal creation notifications (dev)
> Adds dev `metaverse` and `fashion` gov snapshot config

- src/config/daos/daosProduction.ts
Fixes #54
✨ **Updates**
- `metaverse` (NEON) config for Governance proposal creation notifications (prod)
- `fashion` (Red) config for Governance proposal creation notifications (prod)
> Adds prod `metaverse`, `red` configs for gov snapshot proposal submit

- package.json
- src/applications/floor-sweeper-poll/handlers/endedPollsHandler.ts
> fix type errors on `tsc` stemming from `@prisma/client`

- src/config/applications.ts
- Separates upstream floor sweeper poll bot from localhost development
> fix `FLOOR_SWEEPER_POLL_BOT_ID` logic

- src/config/applications.ts
✨ **Updates**
- Adds a production-specific application ID for `FLOOR_SWEEPER_POLL_BOT_ID`
> Adds production app id for `FLOOR_SWEEPER_POLL_BOT_ID`

- src/config/daos/daosProduction.ts
✨ **Updates**
- Updates production DAO config for `metaverse` and `fashion` to add a `resultChannelID` for `FLOOR_SWEEPER_POLL_BOT`
- Adds `music` DAO config
> Adds `resultChannelID`s for production `FLOOR_SWEEPER_POLL_BOT`

- src/config/applications.ts
- Rolls over `FLOOR_SWEEPER_POLL_BOT_ID`s to the Tribute Labs Discord team
> Rolls over application ids to Tribute Labs team

- package-lock.json
- package.json
- src/http-api/middleware/tributeToolsTxWebhook.ts
- src/http-api/middleware/tributeToolsTxWebhook.unit.test.ts
- src/http-api/types.ts
✨ **Updates**
- Improves JSON payload validation for `/webhook/tribute-tools-tx` HTTP API endpoint
> Zod tribute tools webhook

- prisma/migrations/20220315155849_/migration.sql
- prisma/schema.prisma
⛔️ **Removes**
- DB migration: `TributeToolsTxStatus` from Postgres
> Removes orphan db type

- src/applications/tribute-tools/commands/buy.ts
- src/applications/tribute-tools/commands/buy.unit.test.ts
- Adds `.nonempty()` to `zod` `data: z.array(...)`
> Fixes wrong error when 1155 empty

- package-lock.json
- package.json
- src/applications/tribute-tools/commands/buy.ts
- src/applications/tribute-tools/commands/buy.unit.test.ts
- src/services/index.ts
Fixes #109 
🥳 **Adds**
- `@types/sharp`, `sharp` packages
- `/buy` now converts SVG to PNG images on the fly and displays it in the Discord message
- Updates index imports for `services`
> Adds SVG support for `/buy` assets

- src/applications/tribute-tools/handlers/buy/buyPollReactionHandler.ts
- src/applications/tribute-tools/handlers/buy/buyPollReactionHandler.unit.test.ts
Fixes #118 
✨ **Updates**
- `/buy` exit link now adds `price` in WEI
> Adds `price` to `/buy` exit URL

- src/applications/tribute-tools/commands/buy.ts
- src/applications/tribute-tools/commands/buy.unit.test.ts
- Uses Gem `.../route` to get pricing information as it is the most stable endpoint for ERC-721's and 1155's
> Adds better pricing support for `/buy` from Gem

- src/http-api/helpers/index.ts
- src/http-api/helpers/validateZod.ts
- src/http-api/helpers/validateZod.unit.test.ts
- src/http-api/middleware/tributeTools/index.ts
- src/http-api/middleware/tributeTools/router.ts
- src/http-api/middleware/tributeTools/tributeToolsFeeWebhook.ts
- src/webhook-tasks/actions/index.ts
- src/webhook-tasks/actions/snapshotHub/legacyTributeDraftCreated.ts
- src/webhook-tasks/actions/tributeTools/index.ts
- src/webhook-tasks/actions/tributeTools/notifyAdminFee.ts
Initial work for #119. Pushing to development for quick testing with Tribute Tools. More work to do (config, tests, org, cleanup).
🥳 **Adds**
- `tributeToolsFeeWebhook` Koa Router middleware
- `notifyAdminFee` handler for sending message to Discord
- `validateZod` helper
> Initial work: notify discord channel when admin fee due to be collected

- src/http-api/middleware/tributeTools/tributeToolsFeeWebhook.ts
- src/http-api/middleware/tributeTools/tributeToolsFeeWebhook.unit.test.ts
- src/services/discord/getDiscordWebhookClient.unit.test.ts
- src/webhook-tasks/actions/tributeTools/notifyAdminFee.unit.test.ts
Part of #119 
🥳 **Adds**
-  Unit tests added for `tributeToolsFeeWebhook`, `notifyAdminFee`
✨ **Updates**
- Improves error handling in `tributeToolsFeeWebhook`
- Type fixes for
> Unit tests for #119

- src/http-api/middleware/tributeTools/tributeToolsFeeWebhook.ts
- src/http-api/middleware/tributeTools/tributeToolsFeeWebhook.unit.test.ts
- src/webhook-tasks/actions/tributeTools/notifyAdminFee.ts
- src/webhook-tasks/actions/tributeTools/notifyAdminFee.unit.test.ts
Part of #119
✨ **Updates**
- Adds `totalContribution` to Discord webhook message
> adds `totalContribution` to `notifyAdminFee` discord response

- package-lock.json
- package.json
- src/http-api/middleware/db.unit.test.ts
- src/services/snapshotHub/legacyTributeDraftResolver.unit.test.ts
- src/services/snapshotHub/legacyTributeProposalResolver.unit.test.ts
- src/webhook-tasks/actions/snapshotHub/legacyTributeDraftCreated.unit.test.ts
- src/webhook-tasks/actions/snapshotHub/legacyTributeGovernanceProposalCreatedAction.unit.test.ts
- test/msw/serverHandlersREST.ts
- Updates `msw` a major version and fixes any broken tests as a result
> npm major `msw`

- src/config/discords/daos/daosProduction.ts
Fixes #136
- Update production DAO configurations to add a config for `spaceship`
> Adds initial production configuration for spaceship dao

- src/applications/tribute-tools/commands/buy.ts
- src/applications/tribute-tools/commands/buy.unit.test.ts
- OpenSea changed their URL structure for assets to include the token types and/or chains they support. In this case adding `.../ethereum/...`.
> Fixes OS url as it was updated to include a new path

- package-lock.json
- package.json
- src/applications/tribute-tools/commands/buy.ts
- src/applications/tribute-tools/commands/buy.unit.test.ts
- src/http-api/middleware/tributeTools/tributeToolsTxWebhook.unit.test.ts
Fixes #143 
- Fixes a bug where accessing the price information for marketplaces other than OpenSea would display an error to the Discord user.
- Updates `zod` package
> Fixes buy price for multiple marketplaces

- README.md
- package-lock.json
- package.json
- Uses `release-it` for production releases and updates `npm run release` command
> Add `release-it`
